### ISSUE TITLE
Easier way to get products

### ISSUE THREAD

**Issue by AdamGrossTX** [varandas/ToolBox#1]
I was looking for some code for managing ADRs today and stumbled on yours.  I noticed that you have hardcoded a bunch or productids and their friendly names. I found a way to pull the names dynamically so you don't have to hardcode anymore.  Sorry, but I don't have the time to do a PR on your code, but here's the test script that I used to prove it out.

```powershell
$ADR = Get-CMAutoDeploymentRule -Name "Server - All Updates"
$XML = [XML]$ADR.UpdateRuleXML
$XML.UpdateXML.UpdateXMLDescriptionItems.UpdateXMLDescriptionItem
$Products = ($xml.UpdateXML.UpdateXMLDescriptionItems.UpdateXMLDescriptionItem | Where-Object {$_.PropertyName -eq "_Product"}).MatchRules.String.Replace("'","")
Get-CMSoftwareUpdateCategory -Fast | where-object {$_.CategoryInstance_UniqueID -in $Products} | Select-Object -ExpandProperty LocalizedCategoryInstanceName
```

Hope this helps, otherwise, please disregard :-)

**Comment by rodrigovarandas** [comment]
Thanks for the suggestion :)
That is script needs a full refresh indeed... I'm sure I would make it entirely different today.

Whenever I do it, I will bring your suggestion in the mix!
